#! /bin/bash
echo
echo "Removing Database"
echo
rm -Rfv  /Users/ron/NetBeansProjects/VoipStorm/data/databases/*
echo
echo "Removing ./dist/data/databases/Database"
echo
rm -Rfv  /Users/ron/NetBeansProjects/VoipStorm/dist/data/databases/*
echo
echo "Removing Logs"
echo
rm -Rfv  /Users/ron/NetBeansProjects/VoipStorm/data/log/*
rm -Rfv  /Users/ron/NetBeansProjects/VoipStorm/dist/data/log/*
echo
echo "Copy data > ./dist/"
echo
rsync -av --progress --delete /Users/ron/NetBeansProjects/VoipStorm/data /Users/ron/NetBeansProjects/VoipStorm/dist/
echo
if [ ! -d /Users/ron/NetBeansProjects/VoipStorm/voipstorm ]; then mkdir /Users/ron/NetBeansProjects/VoipStorm/voipstorm; fi
echo
echo "Copy ./dist/. to voipstorm archive dir"
echo
rsync -av --progress --delete /Users/ron/NetBeansProjects/VoipStorm/dist/ /Users/ron/NetBeansProjects/VoipStorm/voipstorm/
echo
echo "Remove Apple DS_Store"
echo
find /Users/ron/NetBeansProjects/VoipStorm/voipstorm/ -name ".DS_Store" -delete
echo
echo "Remove NB README.TXT"
echo
find /Users/ron/NetBeansProjects/VoipStorm/voipstorm/ -name "README.TXT" -delete
echo
echo "Copy VoipStorm Readme.html"
echo
rsync -av --progress --delete /Users/ron/NetBeansProjects/VoipStorm/Readme.html /Users/ron/NetBeansProjects/VoipStorm/voipstorm/
echo
echo "Remove Old VoipStorm Package"
echo
rm -v /Users/ron/voipstorm.zip
cd /Users/ron/NetBeansProjects/VoipStorm
echo
echo "Move voipstorm to Home"
echo
rsync -av --progress --delete /Users/ron/NetBeansProjects/VoipStorm/voipstorm /Users/ron/
cd /Users/ron/NetBeansProjects/VoipStorm
echo
echo "Create VoipStorm Packge Zip Archive"
echo
zip -r /Users/ron/voipstorm.zip voipstorm
echo
echo "Removing ../VoipStorm/voipstorm Directory"
echo
rm -Rf /Users/ron/NetBeansProjects/VoipStorm/voipstorm/
echo
echo "Removing ./dist/"
echo
rm -Rfv  /Users/ron/NetBeansProjects/VoipStorm/dist/*


cd ~/voipstorm
