#! /bin/bash

export destin=/Users/ron/voipstorm/

rm -Rf $destin/data/databases/*
rm -Rf $destin/data/log/*

#cp license.xml $destin/data/license/

cd $destin
java -Xmx512m -client -jar VoipStorm.jar &
#java -Xprof -Xmx512m -client -jar VoipStorm.jar &
