#! /bin/bash

export destin=/Users/ron/voipstorm/

rm -Rf $destin/data/databases/*
rm -Rf $destin/data/log/*

cp -r VoipStormDB $destin/data/databases/
cp license.xml $destin/data/license/

cd $destin
java -client -jar VoipStorm.jar &
